#!/bin/bash

set -x
echo "start http server"

SIT_DIR=${SIT_DIR:-"site"}
HTTP_PORT=${HTTP_PORT:-"80"}
INTERFACE=${INTERFACE:-"eth0"}

echo "http root: ${SIT_DIR}"
echo "http port: ${HTTP_PORT}"
echo "interface: ${INTERFACE}"

MAIN_V4_IP=` ip -4 addr show ${INTERFACE} | grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}' | head -1 `
MAIN_V6_IP=` ip -6 addr show ${INTERFACE} | grep -v "scope link" | grep -oP '(?<=inet6\s)[0-9a-f:]+' | head -1 `
# show whether ipv6 is ready
sysctl  net.ipv6.conf.all.disable_ipv6
ip a

mkdir -p ${SIT_DIR}
if [ ! -f "${SIT_DIR}/index.html" ] ; then
    echo "generate index.html "
    echo "this is netknife, ipv4=$MAIN_V4_IP, ipv6=$MAIN_V6_IP" > ${SIT_DIR}/index.html
fi

# listen on 0.0.0.0 and ::
caddy file-server --listen :${HTTP_PORT} --root ${SIT_DIR}
echo "error, http server failed to run" && exit 1
