name: Badge Status

env:
  CODESTATUSSCRIPT: "./tools/codeCoverage.sh"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download cloc
        run: sudo apt-get update -y && sudo apt-get install -y cloc

      - name: Get the Numbers
        shell: bash
        run: |
          TOOL_PATH=${{ env.CODESTATUSSCRIPT }}
          CODE_LINES=$(  ${TOOL_PATH} --code-lines )
          COMMENT_PERCENTAGE=$(  ${TOOL_PATH} --comment-percent )
          echo "CODE_LINES=${CODE_LINES}" >> $GITHUB_ENV
          echo "COMMENT_PERCENTAGE=${COMMENT_PERCENTAGE}" >> $GITHUB_ENV

      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
          auth: ${{ secrets.WELAN_PAT }}
          gistID: d0f9348f23d4a0c20d369a3d27e7cd3f
          filename: netknifecodeline.json
          label: Code Lines
          message: ${{ env.CODE_LINES }}
          color: lightgrey
